# Memory Builder Configuration
# Processes YAML profiles into JSONL entities for Claude's Memory System

build:
  process:
    additionalProfiles: false
    commonProfilesFirst: true
    stopOnCriticalError: true
  outputPath: ./graph.json
  profiles:
    - creative.yaml
    - developer.yaml
    - engineer.yaml
    - humanist.yaml
    - researcher.yaml
    - translator.yaml
  profilesPath:
    common: ./profiles/common
    domain: ./profiles
  relations:
    - extends
    - inherits
    - overrides

logging:
  showFileDetails: true
  showProgress: true

path:
  conversations: /Users/ben/code/claude-private-memory/.claude/data/conversations
  diary: /Users/ben/code/claude-private-memory/.claude/data/diary
  tool: /Users/ben/code/claude-collab/.claude/tools/memory
